const twilio = require('twilio');
const historyService = require('./historyService');
const openaiService = require('./openaiService');
const scheduleService = require('./scheduleService');

// Initialize Twilio Client
const client = twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN);

class OutboundService {
    async sendInitialMessage(contact, agentConfig) {
        try {
            const { name, phone } = contact;
            const { name: agentName, company } = agentConfig;

            // Check if within schedule
            const schedule = agentConfig.schedule;
            if (schedule && !scheduleService.isWithinSchedule(schedule)) {
                const nextSlot = scheduleService.getNextAvailableSlot(schedule);
                console.log(`Outside schedule. Message to ${phone} queued for ${nextSlot}`);
                
                // TODO: Implement message queue for scheduled delivery
                // For now, we'll just log and skip
                // In production, you'd want to use a job queue like Bull/Redis
                return { success: false, queued: true, scheduledFor: nextSlot };
            }

            // Construct initial message
            // TODO: Allow customizing this template in agent config
            // 1. Determine which template to use
            // 1. Determine which template to use
            let messageBody = '';
            let usedAiGeneration = false;

            // Check for Source-Specific Template (Case Insensitive)
            console.log('Contact Source:', contact.source);

            if (contact.source && agentConfig.source_templates) {
                const sourceKey = Object.keys(agentConfig.source_templates).find(
                    key => key.toLowerCase() === contact.source.toLowerCase()
                );

                if (sourceKey) {
                    const template = agentConfig.source_templates[sourceKey];
                    if (template && template.trim() !== '') {
                        messageBody = template;
                        console.log('Using Source Template:', messageBody);
                    }
                }
            }

            // If no specific template found, check for default template OR use AI
            if (!messageBody) {
                if (agentConfig.first_message_template && agentConfig.first_message_template.trim() !== '') {
                    messageBody = agentConfig.first_message_template;
                    console.log('Using Default Static Template:', messageBody);
                } else {
                    // AI FALLBACK
                    console.log('No template found. Generating AI Initial Message...');
                    messageBody = await openaiService.generateInitialMessage(agentConfig, contact);
                    usedAiGeneration = true;
                    console.log('Generated AI Message:', messageBody);
                }
            }

            // 2. Replace Variables (Only if NOT generated by AI, as AI already has context)
            if (!usedAiGeneration) {
                messageBody = messageBody
                    .replace(/{{name}}/g, contact.name || '')
                    .replace(/{{company}}/g, contact.company_name || '')
                    .replace(/{{job}}/g, contact.job_title || '');
            }

            console.log(`Sending outbound SMS to ${phone}: ${messageBody}`);

            // 3. Send SMS
            const message = await client.messages.create({
                body: messageBody,
                from: process.env.TWILIO_PHONE_NUMBER,
                to: contact.phone
            });

            // 4. Save to History (with agent_id from contact)
            await historyService.saveMessage(phone, 'assistant', messageBody, contact.agent_id);

            return true;
        } catch (error) {
            console.error('Error sending outbound SMS:', error);
            return false;
        }
    }
}

module.exports = new OutboundService();
